FROM python:slim

# Run as non-root user
USER 0
RUN useradd -m -d /app appuser -u 1001

WORKDIR /app

USER 1001

ARG exporter_version
COPY dist/pure-fa-openmetrics-exporter-${exporter_version}.tar.gz .
COPY src/pure_fa_openmetrics_exporter/pure_fa_exporter.py .

# Install package - dependencies are already included in the package itself
RUN pip install --upgrade pip && \
    pip install --no-cache-dir pure-fa-openmetrics-exporter-${exporter_version}.tar.gz && \
    rm pure-fa-openmetrics-exporter-${exporter_version}.tar.gz

ENV PATH "$PATH:/app/.local/bin"

EXPOSE 9490
ENTRYPOINT ["/app/pure_fa_exporter.py"]
CMD ["--host", "0.0.0.0", "--port", "9490", "--disable-cert-warning"]
