{
 "title": "Pure Storage FlashArray - Overview",
 "tags": [
  "pure storage",
  "flasharray",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "env", "label": "Env", "query": { "query": "query_result(purefa_info)" } },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": {
     "query": "query_result(purefa_info{instance=~\".+\"})"
    }
   },
   { "name": "TopItems", "label": "Top Items", "query": "1,2,3,4,5,6,7,8,10,15,25,50" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "options": {
    "content": "<img src=\"https://raw.githubusercontent.com/DataDog/integrations-extras/master/purefa/images/widget_logo.png\">"
   }
  },
  {
   "title": "FlashArray System Detail",
   "type": "table",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(purefa_info{instance=~\"$instance\",env=~\"$env\"}) by (instance,os,version)",
     "legendFormat": "Version"
    },
    {
     "expr": "sum(purefa_alerts_open{instance=~\"$instance\",env=~\"$env\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefa_array_space_data_reduction_ratio{instance=~\"$instance\",env=~\"$env\"}) by (instance)",
     "legendFormat": "Data Reduction"
    },
    {
     "expr": "sum(purefa_array_space_bytes{instance=~\"$instance\",env=~\"$env\",space=\"capacity\"}) by (instance) /1024/1024/1024/1024",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(purefa_array_space_bytes{instance=~\"$instance\",env=~\"$env\",space=\"empty\"}) by (instance) /1024/1024/1024/1024",
     "legendFormat": "Free Capacity (TB)"
    },
    {
     "expr": "sum(purefa_array_space_utilization{instance=~\"$instance\",env=~\"$env\"}) by (instance)",
     "legendFormat": "Utilization %"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "options": {
    "content": "# <b>PURE</b> STORAGE\n\n## Overview\n\nThis dashboard provides performance and capacity details for Pure Storage FlashArrays.\nGroup arrays by customer defined environment, whole fleets, or view arrays individually."
   },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FlashArray System Alerts",
   "type": "table",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\", severity=\"info\"}) by (instance) OR on() sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\"}*0) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\", severity=\"warning\"}) by (instance) OR on() sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\"}*0) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\", severity=\"critical\"}) by (instance) OR on() sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\"}*0) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\", severity=\".*\"}) by (instance) OR on() sum(purefa_alerts_open{instance=~\"$instance\", env=~\"$env\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Total Bandwidth for $instance array(s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_bandwidth_bytes{instance=~\"^$instance\",env=~\"^$env\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Data Reduction Ratio for $instance array(s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": ":1" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_space_data_reduction_ratio{instance=~\"^$instance\",env=~\"^$env\"})"
    }
   ]
  },
  {
   "title": "Average Array Utilization for $instance array(s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(purefa_array_space_utilization{instance=~\"$instance\",env=~\"$env\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 26, "w": 6, "x": 0, "y": 9 },
   "options": {
    "content": "## Metrics\n\nAll metrics are prefixed with purefa_\nBelow are the metrics names available\n```\n* alerts_open\n* array_performance_average_bytes\n* array_performance_bandwidth_bytes\n* array_performance_latency_usec\n* array_performance_queue_depth_ops\n* array_performance_throughput_iops\n* array_space_bytes\n* array_space_data_reduction_ratio\n* array_space_utilization\n* directory_performance_average_bytes\n* directory_performance_bandwidth_bytes\n* directory_performance_latency_usec\n* directory_performance_throughput_iops\n* directory_space_bytes\n* directory_space_data_reduction_ratio\n* host_connections_info\n* host_performance_average_bytes\n* host_performance_bandwidth_bytes\n* host_performance_latency_usec\n* host_performance_throughput_iops\n* host_space_bytes\n* host_space_data_reduction_ratio\n* host_space_size_bytes\n* hw_component_status\n* hw_component_temperature_celsius\n* hw_component_voltage_volt\n* info\n* pod_performance_average_bytes\n* pod_performance_bandwidth_bytes\n* pod_performance_latency_usec\n* pod_performance_throughput_iops\n* pod_space_bytes\n* pod_space_data_reduction_ratio\n* volume_performance_average_bytes\n* volume_performance_bandwidth_bytes\n* volume_performance_latency_usec\n* volume_performance_throughput_iops\n* volume_space_bytes\n* volume_space_data_reduction_ratio\n```"
   }
  },
  {
   "title": "Sum of Space Utilization by $instance array(s)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (purefa_array_space_bytes{instance=~\"^$instance\",env=~\"^$env\",space=~\"system|replication|shared|snapshots|unique|empty\"}) by(space)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average IOPS by IO Type and $instance array(s)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_throughput_iops{instance=~\"^$instance\",env=~\"^$env\"}[$__range])) by (dimension)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Bandwidth by $instance array(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_bandwidth_bytes{env=~\"^$env\", instance=~\"^$instance\", dimension=\"write_bytes_per_sec\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Bandwidth by $instance array(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_bandwidth_bytes{env=~\"^$env\", instance=~\"^$instance\", dimension=\"read_bytes_per_sec\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Top $TopItems Latent Volumes by $instance array(s) & IO type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(purefa_volume_performance_latency_usec{env=~\"$env\", instance=~\"$instance\"}) by (instance,dimension,name)\nand\ntopk($TopItems, avg(rate(purefa_volume_performance_latency_usec{env=~\"$env\", instance=~\"$instance\"}[$__range] @ end() )) by (instance,dimension,name))",
     "legendFormat": "{{instance}} - {{dimension}} - {{name}}"
    }
   ]
  },
  {
   "title": "Array QDepth by $instance array(s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "op" } },
   "targets": [
    {
     "expr": "avg(purefa_array_performance_queue_depth_ops{instance=~\"^$instance\",env=~\"^$env\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Top $TopItems Read Throughput by $instance array(s) & Hosts ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "avg(purefa_host_performance_throughput_iops{env=~\"$env\", instance=~\"$instance\", dimension=\"reads_per_sec\"}) by (instance,host)\nand\ntopk($TopItems, avg(rate(purefa_host_performance_throughput_iops{env=~\"$env\", instance=~\"$instance\", dimension=\"reads_per_sec\"}[$__range] @ end() )) by (instance,host))",
     "legendFormat": "{{instance}}  - {{host}}"
    }
   ]
  },
  {
   "title": "Average Top $TopItems Write Throughput by $instance array(s) & Hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "avg(purefa_host_performance_throughput_iops{env=~\"$env\", instance=~\"$instance\", dimension=\"writes_per_sec\"}) by (instance,host)\nand\ntopk($TopItems, avg(rate(purefa_host_performance_throughput_iops{env=~\"$env\", instance=~\"$instance\", dimension=\"writes_per_sec\"}[$__range] @ end() )) by (instance,host))",
     "legendFormat": "{{instance}} - {{host}}"
    }
   ]
  },
  {
   "title": "Latency by $instance array(s) IO Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "purefa_array_performance_latency_usec{instance=~\"$instance\",env=~\"$env\"}\nand \ntopk($TopItems,rate(purefa_array_performance_latency_usec{instance=~\"$instance\",env=~\"$env\"}[$__range] @ end() ))",
     "legendFormat": "{{instance}}  - {{dimension}}"
    }
   ]
  },
  {
   "title": "Throughput by $instance array(s) IO Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "purefa_array_performance_throughput_iops{instance=~\"$instance\",env=~\"$env\"}\nand \ntopk($TopItems,rate(purefa_array_performance_throughput_iops{instance=~\"$instance\",env=~\"$env\"}[$__range] @ end() ))",
     "legendFormat": "{{instance}}  - {{dimension}}"
    }
   ]
  },
  {
   "title": "Bandwidth by $instance array(s) IO Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "purefa_array_performance_bandwidth_bytes{instance=~\"$instance\",env=~\"$env\"}\nand \ntopk($TopItems,rate(purefa_array_performance_bandwidth_bytes{instance=~\"$instance\",env=~\"$env\"}[$__range] @ end() ))",
     "legendFormat": "{{instance}}  - {{dimension}}"
    }
   ]
  }
 ]
}